<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Post extends Model
{
    /**
     * attributes that can be mass assignable
     * @var string[]
     */
    protected $fillable =['title','description','type','text','acesses','edit_reason','author_id'];

    /**
     * get user who created this post
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function author(){
        return $this->belongsTo(User::class);
    }

    /**
     * When creating a record automatically creates a slug based on title
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        parent::creating(function ($post){
            $post->slug = Str::slug($post->title);
        });
    }


}
